app:
  jwt:
    secret: "change-me-to-a-long-random-256bit-secret-string"
    expirationMillis: 86400000 # 1 day

spring:
  datasource:
    url: jdbc:h2:mem:restodb;DB_CLOSE_DELAY=-1;MODE=LEGACY
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none   # ❌ turn off auto-DDL
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2
  server:
    port: 8080
    servlet:
      context-path: /catering

  # CORS: allow local dev frontends
  app:
    cors:
      origins: "http://localhost:5173,http://localhost:3000"

  flyway:
    enabled: true
    baseline-on-migrate: true