CREATE TABLE restaurant (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255),
    takeaway BOOLEAN,
    delivery BOOLEAN,
    hours_json CLOB
);

CREATE TABLE menu_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    prep_mins INT NOT NULL,
    active BOOLEAN NOT NULL,
    restaurant_id BIGINT,
    CONSTRAINT fk_restaurant FOREIGN KEY (restaurant_id) REFERENCES restaurant(id)
);

CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP,
    eta_mins INT,
    total DOUBLE PRECISION,
    status VARCHAR(20),
    note VARCHAR(1000)
);

CREATE TABLE order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_item_id BIGINT,
    name VARCHAR(255),
    qty INT,
    price DOUBLE PRECISION,
    prep_mins INT,
    order_id BIGINT,
    CONSTRAINT fk_order FOREIGN KEY (order_id) REFERENCES orders(id)
);
